name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.26
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          base_indepth: <default-value>
          base_hireable: <default-value>
          repositories: <default-value>
          repositories_batch: <default-value>
          repositories_forks: <default-value>
          repositories_affiliations: <default-value>
          repositories_skipped: <default-value>
          users_ignored: <default-value>
          commits_authoring: <default-value>
          repo: <default-value>
          committer_token: ***
          committer_branch: <default-value>
          committer_message: <default-value>
          committer_gist: <default-value>
          filename: <default-value>
          markdown: <default-value>
          markdown_cache: <default-value>
          output_action: <default-value>
          output_condition: <default-value>
          optimize: <default-value>
          setup_community_templates: <default-value>
          query: <default-value>
          extras_css: <default-value>
          extras_js: <default-value>
          config_order: <default-value>
          config_twemoji: <default-value>
          config_gemoji: <default-value>
          config_octicon: <default-value>
          config_display: <default-value>
          config_animations: <default-value>
          config_base64: <default-value>
          config_padding: <default-value>
          config_output: <default-value>
          retries: <default-value>
          retries_delay: <default-value>
          retries_output_action: <default-value>
          retries_delay_output_action: <default-value>
          clean_workflows: <default-value>
          delay: <default-value>
          quota_required_rest: <default-value>
          quota_required_graphql: <default-value>
          quota_required_search: <default-value>
          notice_releases: <default-value>
          use_prebuilt_image: yes
          plugins_errors_fatal: <default-value>
          debug: <default-value>
          verify: <default-value>
          debug_flags: <default-value>
          debug_print: <default-value>
          dryrun: <default-value>
          experimental_features: <default-value>
          use_mocked_data: <default-value>
          plugin_languages_ignored: <default-value>
          plugin_languages_skipped: <default-value>
          plugin_languages_other: <default-value>
          plugin_languages_aliases: <default-value>
          plugin_languages_indepth: <default-value>
          plugin_topics: <default-value>
          plugin_topics_mode: <default-value>
          plugin_topics_sort: <default-value>
          plugin_topics_limit: <default-value>
          plugin_licenses: <default-value>
          plugin_licenses_setup: <default-value>
          plugin_licenses_ratio: <default-value>
          plugin_licenses_legal: <default-value>
          plugin_habits: <default-value>
          plugin_habits_from: <default-value>
          plugin_habits_days: <default-value>
          plugin_habits_facts: <default-value>
          plugin_habits_charts: <default-value>
          plugin_habits_charts_type: <default-value>
          plugin_habits_trim: <default-value>
          plugin_habits_languages_limit: <default-value>
          plugin_contributors: <default-value>
          plugin_contributors_base: <default-value>
          plugin_contributors_head: <default-value>
          plugin_contributors_ignored: <default-value>
          plugin_contributors_contributions: <default-value>
          plugin_contributors_sections: <default-value>
          plugin_contributors_categories: <default-value>
          plugin_followup_indepth: <default-value>
          plugin_followup_archived: <default-value>
          plugin_reactions: <default-value>
          plugin_reactions_limit: <default-value>
          plugin_reactions_limit_issues: <default-value>
          plugin_reactions_limit_discussions: <default-value>
          plugin_reactions_limit_discussions_comments: <default-value>
          plugin_reactions_days: <default-value>
          plugin_reactions_display: <default-value>
          plugin_reactions_details: <default-value>
          plugin_reactions_ignored: <default-value>
          plugin_people: <default-value>
          plugin_people_limit: <default-value>
          plugin_people_identicons: <default-value>
          plugin_people_identicons_hide: <default-value>
          plugin_people_size: <default-value>
          plugin_people_types: <default-value>
          plugin_people_thanks: <default-value>
          plugin_people_sponsors_custom: <default-value>
          plugin_people_shuffle: <default-value>
          plugin_stargazers: <default-value>
          plugin_stargazers_charts_type: <default-value>
          plugin_projects: <default-value>
          plugin_projects_limit: <default-value>
          plugin_projects_repositories: <default-value>
          plugin_projects_descriptions: <default-value>
          plugin_code: <default-value>
          plugin_code_lines: <default-value>
          plugin_code_load: <default-value>
          plugin_code_days: <default-value>
          plugin_code_visibility: <default-value>
          plugin_code_skipped: <default-value>
          plugin_code_languages: <default-value>
          plugin_activity_timestamps: <default-value>
          plugin_activity_skipped: <default-value>
          plugin_activity_ignored: <default-value>
          plugin_achievements_limit: <default-value>
          plugin_achievements_ignored: <default-value>
          plugin_achievements_only: <default-value>
          plugin_notable: <default-value>
          plugin_notable_filter: <default-value>
          plugin_notable_skipped: <default-value>
          plugin_notable_from: <default-value>
          plugin_notable_repositories: <default-value>
          plugin_notable_indepth: <default-value>
          plugin_notable_types: <default-value>
          plugin_discussions: <default-value>
          plugin_discussions_categories: <default-value>
          plugin_discussions_categories_limit: <default-value>
          plugin_support: <default-value>
          plugin_lines_skipped: <default-value>
          plugin_traffic: <default-value>
          plugin_traffic_skipped: <default-value>
          plugin_repositories: <default-value>
          plugin_repositories_featured: <default-value>
          plugin_repositories_pinned: <default-value>
          plugin_gists: <default-value>
          plugin_introduction: <default-value>
          plugin_introduction_title: <default-value>
          plugin_sponsors: <default-value>
          plugin_sponsors_sections: <default-value>
          plugin_sponsors_past: <default-value>
          plugin_sponsors_size: <default-value>
          plugin_starlists: <default-value>
          plugin_starlists_limit: <default-value>
          plugin_starlists_limit_repositories: <default-value>
          plugin_starlists_languages: <default-value>
          plugin_starlists_limit_languages: <default-value>
          plugin_starlists_shuffle_repositories: <default-value>
          plugin_starlists_ignored: <default-value>
          plugin_starlists_only: <default-value>
          plugin_calendar: <default-value>
          plugin_calendar_limit: <default-value>
          plugin_skyline: <default-value>
          plugin_skyline_year: <default-value>
          plugin_skyline_frames: <default-value>
          plugin_skyline_quality: <default-value>
          plugin_skyline_compatibility: <default-value>
          plugin_pagespeed: <default-value>
          plugin_pagespeed_token: <default-value>
          plugin_pagespeed_url: <default-value>
          plugin_pagespeed_detailed: <default-value>
          plugin_pagespeed_screenshot: <default-value>
          plugin_pagespeed_pwa: <default-value>
          plugin_stackoverflow: <default-value>
          plugin_stackoverflow_user: <default-value>
          plugin_stackoverflow_sections: <default-value>
          plugin_stackoverflow_limit: <default-value>
          plugin_stackoverflow_lines: <default-value>
          plugin_stackoverflow_lines_snippet: <default-value>
          plugin_anilist: <default-value>
          plugin_anilist_user: <default-value>
          plugin_anilist_medias: <default-value>
          plugin_anilist_sections: <default-value>
          plugin_anilist_limit: <default-value>
          plugin_anilist_limit_characters: <default-value>
          plugin_anilist_shuffle: <default-value>
          plugin_tweets: <default-value>
          plugin_tweets_token: <default-value>
          plugin_tweets_user: <default-value>
          plugin_tweets_attachments: <default-value>
          plugin_tweets_limit: <default-value>
          plugin_posts: <default-value>
          plugin_posts_source: <default-value>
          plugin_posts_user: <default-value>
          plugin_posts_descriptions: <default-value>
          plugin_posts_covers: <default-value>
          plugin_posts_limit: <default-value>
          plugin_music: <default-value>
          plugin_music_provider: <default-value>
          plugin_music_token: <default-value>
          plugin_music_user: <default-value>
          plugin_music_mode: <default-value>
          plugin_music_playlist: <default-value>
          plugin_music_limit: <default-value>
          plugin_music_played_at: <default-value>
          plugin_music_time_range: <default-value>
          plugin_music_top_type: <default-value>
          plugin_rss: <default-value>
          plugin_rss_source: <default-value>
          plugin_rss_limit: <default-value>
          plugin_wakatime: <default-value>
          plugin_wakatime_token: <default-value>
          plugin_wakatime_url: <default-value>
          plugin_wakatime_user: <default-value>
          plugin_wakatime_sections: <default-value>
          plugin_wakatime_days: <default-value>
          plugin_wakatime_limit: <default-value>
          plugin_wakatime_languages_other: <default-value>
          plugin_wakatime_languages_ignored: <default-value>
          plugin_wakatime_repositories_visibility: <default-value>
          plugin_fortune: <default-value>
          plugin_nightscout: <default-value>
          plugin_nightscout_url: <default-value>
          plugin_nightscout_datapoints: <default-value>
          plugin_nightscout_lowalert: <default-value>
          plugin_nightscout_highalert: <default-value>
          plugin_nightscout_urgentlowalert: <default-value>
          plugin_nightscout_urgenthighalert: <default-value>
          plugin_poopmap: <default-value>
          plugin_poopmap_token: <default-value>
          plugin_poopmap_days: <default-value>
          plugin_screenshot: <default-value>
          plugin_screenshot_title: <default-value>
          plugin_screenshot_url: <default-value>
          plugin_screenshot_selector: <default-value>
          plugin_screenshot_background: <default-value>
          plugin_stock: <default-value>
          plugin_stock_token: <default-value>
          plugin_stock_symbol: <default-value>
          plugin_stock_duration: <default-value>
          plugin_stock_interval: <default-value>
